name: Format and Clean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black-and-nbstripout:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black nbstripout

      - name: Run Black
        run: black .

      - name: Strip Jupyter notebooks
        run: |
          find . -name "*.ipynb" -exec nbstripout {} \;

      - name: Check for changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ -n $(git status --porcelain) ]]; then
            echo "Pliki wymagają ponownego zatwierdzenia po formatowaniu/oczyszczeniu."
            echo "Proszę zrób commit i push ponownie."
            git diff
            exit 1
          fi
